print("Kevin:Hey bruh")
print("Omar:Oh kevin, Assalamualikum brother")
print("Kevin: Ye, May jesus have mercy on you")
print("Omar:Who?")
print("Kevin:Jesus,The God of the world")
print("Omar:God of the world you say")
print("kevin:Yeah lad, God of the world")
print("Kevin: revert to jesus, He loves yoy, youre not late")
print("Omar: How would you say that he is the god..Where did you read it from?")
print("Kevin: That's what trinity says")
print("Omar: The trinity says that there t=are three Gods, The father, the Son and The HolySpirtit But why do you only say that Jesus is god ")
print("Kevin:....Aaaaaa")
print("Omar: Jesus never claimed divinity..")
print("Omar: There is no word such as 'trinity' in the complete bible...if ypu snacth out a single unequable statement or a single unambguess statement that says the world trinity, i shall walk away")
print("Kevin: What do you mean that jesus never claimed divinity?")
print("Omar:Just like the unmentioning of Trinity, There is no mentioning in the complete bible where jesus christ (pbuh) himself says that i am God or where he says worship me..")
print("Omar: If you can prove me a single unambigous statement in the complete bible where jesus christ(pbuh) himself says that he is God or where he says worsip me i am ready to exept CHRISTIANITY")
print("Kevin: Okay man i cant prove i admit..what should i do now ?")
print("Omar: Repeat after me and you shall be a muslim")
print("Kevin: Okay!")
print("Omar:Ashahadu..")
print("Kevin:Ashahadu")
print("Omar:Alla")
print("Kevin: Alla")
print("Omar:Ilaha Illahla ")
print("Kevin:Ilaha ilallah")
print("Omar: Muhammadur-rasoolallah")
print("Kevin: Muhammadur-rasoolalah")
print("Omar: Mashallah my brother abdullah")
print("Abdullah:Allahuakbar")
